In [2]:
import numpy as np

**Numpy array vs List**

array is more memory effcient

In [3]:
# creating list and array
list_ = range(50)
arr = np.arange(50)

In [4]:
import sys

In [5]:
print(sys.getsizeof(45)*len(list_))

1400


In [6]:
print(arr.size*arr.itemsize)

200


**Indexing, Slicing and Iteration**

**1. INDEXING and SLICING:**

In [7]:
arr2= np.arange(30).reshape(5,6) # reshaping the array in 5 rows , 6 columns format
print(arr2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [8]:
arr2[2] # getting 3rd (2nd index) row values (Indexing)

array([12, 13, 14, 15, 16, 17])

In [9]:
# getting a particular value
arr2[2,4] # getting a value from 3rd (2nd index) row and 5th(4th index) column

16

**1.1 SLICING**

In [10]:
# getting 3rd column values. 
arr2[:, 2] 

array([ 2,  8, 14, 20, 26])

In [11]:
# getting 3rd and 4th column values. (Slicing) 
arr2[:, 2:4] 

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27]])

In [12]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [13]:
# Row, Columns 
arr2[2:4, 1:3] # after :, last index number is not included. 

array([[13, 14],
       [19, 20]])

**2. ITERATION**

In [14]:
# for printing all elements one by one
for i in np.nditer(arr2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
