In [2]:
import numpy as np

**Creating Numpy/ n-d arrays**

In [3]:
# sending a list into numpy array fucntion to create a numpy array
arr= np.array([1,2,3,4,3,4]) # creates 1d array
display(arr)
display(type(arr))

array([1, 2, 3, 4, 3, 4])

numpy.ndarray

In [4]:
# creating a 2d array
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3= np.zeros([3,2]) # creating with zeros fucntion
arr3

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
arr4 = np.ones([3,3], dtype= int) # creating with ones function
arr4

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
# The identity array is a square array with ones on the main diagonal.
arr5=  np.identity(5) 
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

By default ***ones()*** , ***zeros()***, ***identity()*** function produces float data type. use ***dtype*** argument to chnage it to int type

In [8]:
# creates a range of array with start, stop and step arguments. 
# like range arguments in for()
np.arange(0, 5, 0.5, dtype=float) 

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
# Return evenly spaced numbers over a specified interval (start, stop).
np.linspace(1,5,10) # produces 10 numbers in between 1 to 5 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [10]:
# copy() to coppy an arraay
arr6 = np.copy(arr2)
arr6

array([[1, 2, 3],
       [4, 5, 6]])

**Atributes of Numpy array**

In [13]:
# to know about the shape of the array
arr5.shape

(5, 5)

In [20]:
arr7= np.array([[[1,2],[2,3]], [[78,65],[6655,23]]]) # creating a 3D array
display(arr7) 
display(arr7.shape) # shape of 3d array

array([[[   1,    2],
        [   2,    3]],

       [[  78,   65],
        [6655,   23]]])

(2, 2, 2)

In [21]:
arr7.ndim # dimension of the array 

3

In [22]:
# size() to know about the no of elements present in the array
display(arr7.size)
display(arr3.size)

8

6

In [32]:
display(arr3) # float 
display(arr4) # int

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
# length of the array elements in bytes
display(arr3.itemsize) # float 
display(arr4.itemsize) # int

8

4

In [33]:
# datatype
display(arr3.dtype) # float 
display(arr4.dtype) # int

dtype('float64')

dtype('int32')

In [38]:
# Changing data type
x = arr4.astype(float)
x.dtype

dtype('float64')